import numpy as np

class Metrics:
    """Class with functions to get all the different metrics we need
    """

    def __roundClosest(a, b):
        """Round a to the closest multiple of b
        """

        return b * round(a/b)

    def avgSpeed(carData: list):
        """Calculate average speed for each time step

        Args:
            carData: list with cars for each time step (generated by the simulation)
        
        Returns: list with average speed for each time step
        """

        avgList = []
        for data_t in carData:
            speedArray = np.array([car['v'] * 3.6 for car in data_t])
            avgList.append(np.average(speedArray))
        return avgList

    def medianSpeed(carData: list):
        """Calculate median speed for each time step

        Args:
            carData: list with cars for each time step (generated by the simulation)
        
        Returns: list with median speed for each time step
        """

        medianList = []
        for data_t in carData:
            speedArray = np.median([car['v'] * 3.6 for car in data_t])
            medianList.append(np.average(speedArray))
        return medianList

    def plotDots(carData: list, roadLength: int, time_div: float, delta_x: float):
        """Car dot plot

        Args:
            carData: list with cars for each time step (generated by the simulation)
            roadLength: length of the road in the simulation
            time_div: time resampling of the data points (use 1 every i-th datapoint)
            delta_x: minimum change in distance (how much distance a pixel represents)
        """

        pixelPlot = np.zeros((len(carData[::time_div]), round(roadLength/delta_x)))
        for i, data_t in enumerate(carData[::time_div]):
            for car in data_t:
                x = int(np.floor(car['pos'][0]/delta_x))
                if car['pos'][1] != 0 or x >= pixelPlot.shape[1]:  continue
                pixelPlot[i][x] = 1
        return pixelPlot
